version: '3'
services:
  # top.api:
  #   build: ./
  #   container_name: top-api
  #   restart: always
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./.env:/app/.env
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_LOGIN}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - 27019:27017
    volumes:
      - ./mongo-data:/data/db
